server:
  port: 8781

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: order-service
  redis:
    database: 0
    host: 192.168.159.128
    port: 6379
    timeout: 2000


product-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

feign:
  client:
    config:
      default:
        connectionTimeout: 5000
        readTimeout: 5000

  hystrix:
    enabled: true